-- The other stuff is here.
USE EventDatabase
GO

-- dirty reads problem.
SET TRANSACTIONSACTION ISOLATION LEVEL READ UNCOMMITTED
BEGIN TRANSACTION
SELECT * FROM Organizers
WAITFOR DELAY '00:00:15'
SELECT * FROM Organizers
COMMIT TRANSACTION

-- dirty reads solution.
SET TRANSACTIONSACTION ISOLATION LEVEL READ COMMITTED
BEGIN TRANSACTION
SELECT * FROM Organizers
WAITFOR DELAY '00:00:15'
SELECT * FROM Organizers
COMMIT TRANSACTION

-- non-repeatable reads problem
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
BEGIN TRANSACTION
SELECT * FROM Organizers
WAITFOR DELAY '00:00:05'
SELECT * FROM Organizers
COMMIT TRANSACTION

-- non-repeatable reads solution
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRANSACTION
SELECT * FROM Organizers
WAITFOR DELAY '00:00:05'
SELECT * FROM Organizers
COMMIT TRANSACTION

-- phantom reads problem
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRANSACTION
SELECT * FROM Organizers
WAITFOR DELAY '00:00:05'
SELECT * FROM Organizers
COMMIT TRANSACTION

--  phantom reads solution
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
BEGIN TRANSACTION
SELECT * FROM Organizers
WAITFOR DELAY '00:00:05'
SELECT * FROM Organizers
COMMIT TRANSACTION

-- deadlock problem
BEGIN TRANSACTION
UPDATE Pariticipants
SET name = 'Update t2'
WHERE oid LIKE '61'
WAITFOR DELAY '00:00:10'
UPDATE Organizers
SET name = 'Update t2'
WHERE pid LIKE '7'
COMMIT TRANSACTION

-- deadlock solution
SET DEADLOCK_PRIORITY HIGH
BEGIN TRANSACTION
UPDATE Pariticipants
SET name = 'Update t2'
WHERE oid LIKE '61'
WAITFOR DELAY '00:00:10'
UPDATE Organizers
SET name = 'Update t2'
WHERE pid LIKE '7'
COMMIT TRANSACTION

-- deadlock second solution
BEGIN TRANSACTION
UPDATE Organizers
SET name = 'Update t2'
WHERE pid LIKE '7'
WAITFOR DELAY '00:00:10'
UPDATE Pariticipants
SET name = 'Update t2'
WHERE oid LIKE '61'
COMMIT TRANSACTION

-- update conflict
USE EventDatabase
GO
SET TRANSACTION ISOLATION LEVEL SNAPSHOT
BEGIN TRANSACTION
SELECT * FROM Organizers WHERE pid LIKE '8'
WAITFOR DELAY '00:00:10'
SELECT * FROM Organizers
UPDATE Organizers SET name = 'Conflict' WHERE pid LIKE '8'
COMMIT TRANSACTION